// Team name → ISO country code (for flag images) and emoji fallback.
const CODES: Record<string, string> = {
    USA: "us",
    "United States": "us",
    Belgium: "be",
    Vietnam: "vn",
    Myanmar: "mm",
    Netherlands: "nl",
    Morocco: "ma",
    Brazil: "br",
    Argentina: "ar",
    France: "fr",
    Germany: "de",
    Spain: "es",
    Portugal: "pt",
    Italy: "it",
    "Bosnia & Herzegovina": "ba",
    Japan: "jp",
    "South Korea": "kr",
    "Korea Republic": "kr",
    Mexico: "mx",
    Canada: "ca",
    Croatia: "hr",
    Uruguay: "uy",
    Colombia: "co",
    Ghana: "gh",
    Nigeria: "ng",
    Senegal: "sn",
    Cameroon: "cm",
    Switzerland: "ch",
    Denmark: "dk",
    Poland: "pl",
    Serbia: "rs",
    Australia: "au",
    Ecuador: "ec",
    Qatar: "qa",
    Iran: "ir",
    "Saudi Arabia": "sa",
    Tunisia: "tn",
    "Costa Rica": "cr",
    Thailand: "th",
    Indonesia: "id",
    Malaysia: "my",
    India: "in",
    China: "cn",
    Egypt: "eg",
    Chile: "cl",
    Peru: "pe",
    Sweden: "se",
    Norway: "no",
    Austria: "at",
    Turkey: "tr",
    Greece: "gr",
    Ukraine: "ua",
    Paraguay: "py",
    "Cape Verde": "cv",
    "Cabo Verde": "cv",
    Algeria: "dz",
    "Congo DR": "cd",
    "DR Congo": "cd",
    "Democratic Republic of the Congo": "cd",
    "Ivory Coast": "ci",
    "Côte d'Ivoire": "ci",
    "South Africa": "za",
    Jordan: "jo",
    Uzbekistan: "uz",
    "New Zealand": "nz",
    Panama: "pa",
    Iraq: "iq",
    Curacao: "cw",
    "Curaçao": "cw",
    Scotland: "gb-sct",
    England: "gb-eng",
    Wales: "gb-wls",
    Liechtenstein: "li",
    Gibraltar: "gi",
};

/** ISO code for a team (for flagcdn image), or null if unknown. */
export function teamCode(name?: string): string | null {
    if (!name) return null;
    return CODES[name] ?? null;
}

const EMOJI: Record<string, string> = {
    us: "🇺🇸", be: "🇧🇪", vn: "🇻🇳", mm: "🇲🇲", nl: "🇳🇱", ma: "🇲🇦", br: "🇧🇷", ar: "🇦🇷",
    fr: "🇫🇷", de: "🇩🇪", es: "🇪🇸", pt: "🇵🇹", it: "🇮🇹", ba: "🇧🇦", jp: "🇯🇵", kr: "🇰🇷",
    mx: "🇲🇽", ca: "🇨🇦", hr: "🇭🇷", uy: "🇺🇾", co: "🇨🇴", gh: "🇬🇭", ng: "🇳🇬", sn: "🇸🇳",
    cm: "🇨🇲", ch: "🇨🇭", dk: "🇩🇰", pl: "🇵🇱", rs: "🇷🇸", au: "🇦🇺", ec: "🇪🇨", qa: "🇶🇦",
    ir: "🇮🇷", sa: "🇸🇦", tn: "🇹🇳", cr: "🇨🇷", th: "🇹🇭", id: "🇮🇩", my: "🇲🇾", in: "🇮🇳",
    cn: "🇨🇳", eg: "🇪🇬", cl: "🇨🇱", pe: "🇵🇪", se: "🇸🇪", no: "🇳🇴", at: "🇦🇹", tr: "🇹🇷",
    gr: "🇬🇷", ua: "🇺🇦", py: "🇵🇾", cv: "🇨🇻", dz: "🇩🇿", cd: "🇨🇩", ci: "🇨🇮", za: "🇿🇦",
    jo: "🇯🇴", uz: "🇺🇿", nz: "🇳🇿", pa: "🇵🇦", iq: "🇮🇶", cw: "🇨🇼",
    li: "🇱🇮",
    gi: "🇬🇮",
};

export function teamFlag(name?: string): string {
    const code = teamCode(name);
    return (code && EMOJI[code]) ?? "⚽";
}
